version: "3.9"
services:
  tp-frontend:
    container_name: tp-frontend
    image: node:14-buster-slim
    volumes:
    - "../training-program-frontend:/usr/src/app"
    - "/usr/src/app/node_modules"
    working_dir: "/usr/src/app"
    command: ["npm", "run", "dev:smart"]
    ports: ["3000:3000"]
    environment:
    - REACT_APP_BACKEND_URL=http://localhost:3001
    - REACT_APP_JWT_SECRET=secret

  tp-backend:
    container_name: tp-backend
    image: node:14-buster-slim
    volumes:
    - "../training-program-backend:/usr/src/app"
    - "/usr/src/app/node_modules"
    working_dir: "/usr/src/app"
    command: ["npm", "run", "dev:smart:with-migrations"]
    ports: ["3001:3001"]
    env_file: .env.backend
    depends_on:
    - tp-database
    environment:
    - DB_HOST=tp-database
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASSWORD=adrian1234
    - DB_DIALECT=postgres

  tp-database:
    container_name: tp-database
    image: postgres:13-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=adrian1234
